/**
 * Machine Details Logic
 * Fetches specific record from Airtable using record ID from URL
 */

const MACHINE_CONFIG = {
    apiKey: 'patzUZXi4xbEcJBtZ.b612407e01e31156ccba38758a352318eae8a69ad628fa26230186c4b30b36a7',
    baseId: 'appkw4hlOEoVJZ7cn',
    tableName: 'machineries',
    categoryTable: 'machine_category',
    technicalTable: 'machine_technical',
    reviewTable: 'machine_review',
    whatsappNumber: '919104183331'
};

const MAIN_CAT_MAP = {
    1: 'Processing Machineries',
    2: 'Packaging Machineries'
};

/**
 * Fetch Data on Page Load
 */
document.addEventListener('DOMContentLoaded', async () => {
    // Check if this is a static page generated by the build script
    if (window.isStaticPage && window.machineData) {
        console.log("Static Page Detected: Using pre-injected data.");
        // Data is already rendered in HTML, but we might need to initialize 
        // interactive elements like Similar Machines or breadcrumbs if they were complex
        // However, the build script handled most of it.
        return;
    }

    const urlParams = new URLSearchParams(window.location.search);
    const recordId = urlParams.get('id');

    if (!recordId) {
        // Fallback for direct access to machine-details.html without ID
        const container = document.getElementById('machine-details-container');
        if (container && container.innerHTML.includes('Fetching')) {
             container.innerHTML = `
                <div class="text-center p-5">
                    <i class="fa-solid fa-triangle-exclamation fa-3x text-warning mb-3"></i>
                    <h3>Machine Not Found</h3>
                    <p>Invalid or missing Machine ID.</p>
                    <a href="machineries.html" class="btn btn-primary mt-3 px-5 rounded-pill">Back to Catalog</a>
                </div>
            `;
        }
        return;
    }

    try {
        const machine = await fetchMachineDetails(recordId);
        if (!machine) throw new Error("Machine fetch failed");

        // Resolve Main Category
        const mainCategoryName = MAIN_CAT_MAP[machine.category] || 'Machinery';

        // Fetch Sub-Category name
        const subCategoryName = await fetchSubCategoryName(machine.sub_category);

        // Fetch technical specs
        const technicalSpecs = await fetchMachineTechnical(machine.product_id || machine.id || recordId);

        // Fetch similar machines
        const similarMachines = await fetchSimilarMachines(machine.category, machine.airtableId);

        renderMachinePage(machine, mainCategoryName, subCategoryName, technicalSpecs, similarMachines);
    } catch (error) {
        console.error("Critical Render Error:", error);
        document.getElementById('machine-details-container').innerHTML = `
            <div class="text-center p-5">
                <i class="fa-solid fa-circle-exclamation fa-3x text-danger mb-3"></i>
                <h3>Error Loading Data</h3>
                <p>Unable to synchronize machine specifications. Please try again later.</p>
            </div>
        `;
    }
});

/**
 * Helper to get image URL from Airtable (String or Attachment Array)
 */
function getProductImages(record) {
    const fieldData = record.image || record.Image || record.ImageURL || record.imageurl;
    if (!fieldData) return ['assets/placeholder-machine.jpg'];
    if (Array.isArray(fieldData) && fieldData.length > 0) {
        return fieldData.map(img => img.url);
    }
    return [fieldData];
}

async function fetchMachineDetails(recordId) {
    const filterFormula = `{id} = "${recordId}"`;
    const url = `https://api.airtable.com/v0/${MACHINE_CONFIG.baseId}/${MACHINE_CONFIG.tableName}?filterByFormula=${encodeURIComponent(filterFormula)}&maxRecords=1`;
    try {
        const response = await fetch(url, {
            headers: { Authorization: `Bearer ${MACHINE_CONFIG.apiKey}` }
        });
        const data = await response.json();

        if (data.records && data.records.length > 0) {
            const record = data.records[0];
            return { airtableId: record.id, ...record.fields };
        }
        return null;
    } catch (error) {
        console.error("Machine Details Error:", error);
        return null;
    }
}

async function fetchSubCategoryName(subCategoryId) {
    if (!subCategoryId) return '';
    // If it's a numeric ID, we search by formula
    const filterFormula = `{id} = ${parseInt(subCategoryId)}`;
    const url = `https://api.airtable.com/v0/${MACHINE_CONFIG.baseId}/${MACHINE_CONFIG.categoryTable}?filterByFormula=${encodeURIComponent(filterFormula)}&maxRecords=1`;
    try {
        const response = await fetch(url, {
            headers: { Authorization: `Bearer ${MACHINE_CONFIG.apiKey}` }
        });
        const data = await response.json();
        if (data.records && data.records.length > 0) {
            return data.records[0].fields.Name || data.records[0].fields.name || '';
        }
        return '';
    } catch (error) {
        console.error("Sub-Category Fetch Error:", error);
        return '';
    }
}

async function fetchMachineTechnical(productId) {
    const numericId = parseInt(productId) || 0;
    const filterFormula = `{product_id} = ${numericId}`;
    const url = `https://api.airtable.com/v0/${MACHINE_CONFIG.baseId}/${MACHINE_CONFIG.technicalTable}?filterByFormula=${encodeURIComponent(filterFormula)}`;
    try {
        const response = await fetch(url, {
            headers: { Authorization: `Bearer ${MACHINE_CONFIG.apiKey}` }
        });
        const data = await response.json();
        return data.records.map(r => r.fields);
    } catch (error) {
        console.error("Technical Specs Error:", error);
        return [];
    }
}

async function fetchSimilarMachines(categoryId, currentId) {
    const id = Array.isArray(categoryId) ? categoryId[0] : categoryId;
    const filterFormula = `AND({category} = "${id}", RECORD_ID() != "${currentId}")`;
    const url = `https://api.airtable.com/v0/${MACHINE_CONFIG.baseId}/${MACHINE_CONFIG.tableName}?filterByFormula=${encodeURIComponent(filterFormula)}&maxRecords=4`;
    try {
        const response = await fetch(url, {
            headers: { Authorization: `Bearer ${MACHINE_CONFIG.apiKey}` }
        });
        const data = await response.json();
        return data.records.map(r => ({ id: r.id, ...r.fields }));
    } catch (error) {
        console.error("Similar Machines Error:", error);
        return [];
    }
}

function renderMachinePage(machine, mainCatName, subCatName, specs, similar) {
    const images = getProductImages(machine);
    const mainName = machine.product_name || machine.Name || machine.name || 'Unnamed Machine';
    const description = machine.description || machine.Description || machine['Description'] || "Detailed description coming soon.";
    const productIdRaw = machine.product_id || machine.id || '000';
    const displayId = `SAL-M-${productIdRaw}`;
    const rawId = machine.id; // Record ID for ratings

    // Update Breadcrumbs (Condensed Style)
    const breadcrumb = document.getElementById('machine-breadcrumb');
    breadcrumb.innerHTML = `
        <li class="breadcrumb-item"><a href="index.html">Home</a></li>
        <li class="breadcrumb-item"><i class="fa-solid fa-chevron-right mx-2 opacity-50 small"></i></li>
        <li class="breadcrumb-item"><a href="machineries.html">Machineries</a></li>
        <li class="breadcrumb-item"><i class="fa-solid fa-chevron-right mx-2 opacity-50 small"></i></li>
        <li class="breadcrumb-item"><a href="machineries.html?cat=${machine.category}">${mainCatName}</a></li>
        <li class="breadcrumb-item"><i class="fa-solid fa-chevron-right mx-2 opacity-50 small"></i></li>
        <li class="breadcrumb-item active text-primary fw-bold" style="color: #ff6b35 !important;">${mainName}</li>
    `;

    const container = document.getElementById('machine-details-container');
    container.innerHTML = `
        <div class="details-grid-condensed">
            <!-- Left Side: Interactive Gallery -->
            <div class="product-gallery d-flex gap-3">
                <div class="thumbnails-column">
                    ${images.map((img, index) => `
                        <div class="thumb-item ${index === 0 ? 'active border-primary' : ''}" onclick="window.switchProductImage('${img}', this)">
                            <img src="${img}" alt="Thumbnail ${index + 1}">
                        </div>
                    `).join('')}
                </div>
                <div class="main-viewport shadow-sm border p-3">
                    <img id="main-product-img" src="${images[0]}" alt="${mainName}" class="img-fluid" style="max-height: 100%; object-fit: contain;">
                </div>
            </div>

            <!-- Right Side: Details & Actions -->
            <div class="details-content">
                <span class="badge-mini mb-2">SKU: ${displayId}</span>
                <h1 class="product-h1 mt-0" style="font-size: 1.5rem !important;">${mainName}</h1>
                
                <div class="rating-display mb-3">
                    <i class="fa-solid fa-star" style="color: #ffc107;"></i>
                    <i class="fa-solid fa-star" style="color: #ffc107;"></i>
                    <i class="fa-solid fa-star" style="color: #ffc107;"></i>
                    <i class="fa-solid fa-star" style="color: #ffc107;"></i>
                    <i class="fa-solid fa-star" style="color: #e2e8f0;"></i>
                </div>

                <div class="product-details-summary mb-4">
                    <p class="section-subtitle-compact mb-2">Product Details:</p>
                    <table class="specs-table-premium">
                        <tr>
                            <td class="spec-label">Category</td>
                            <td class="spec-value">${mainCatName}</td>
                        </tr>
                        ${subCatName ? `
                            <tr>
                                <td class="spec-label">Sub-Category</td>
                                <td class="spec-value">${subCatName}</td>
                            </tr>
                        ` : ''}
                        ${specs.length > 0 ? specs.map(s => `
                            <tr>
                                <td class="spec-label">${s.Title || s.technical_parameter || s.Parameter || 'Spec'}</td>
                                <td class="spec-value">${s.Value || s.value || '-'}</td>
                            </tr>
                        `).join('') : ''}
                    </table>
                </div>

                <div class="action-buttons d-flex gap-3 mb-5">
                    <button class="btn-primary-whatsapp flex-grow-1" onclick="window.orderOnWhatsApp('${displayId}', '${mainName}')">
                        <i class="fa-brands fa-whatsapp me-2"></i> GET A QUOTE
                    </button>
                    <button class="btn-outline-share px-4">
                        <i class="fa-solid fa-share-nodes"></i> Share
                    </button>
                </div>
            </div>
        </div>

        <!-- Accordion Section -->
        <div class="mt-4">
            <div class="accordion-item shadow-sm">
                <button class="accordion-header w-100 d-flex justify-content-between align-items-center p-3 border-0" style="background: #f8fafc;" onclick="window.toggleAccordion(this)">
                    <h5 class="fw-bold mb-0" style="font-size: 1.1rem; color: #1e293b;">Details & Overview</h5>
                    <i class="fa-solid fa-chevron-down opacity-50"></i>
                </button>
                <div class="accordion-content p-4 bg-white" style="display: none; border-top: 1px solid #f1f5f9;">
                    <div class="description-text">
                        ${description.replace(/\n/g, '<br>')}
                    </div>
                </div>
            </div>
        </div>

        <!-- Rating Section -->
        <div class="text-center py-5 border-top mt-5">
            <p class="mb-2 fw-bold small text-muted text-uppercase" style="letter-spacing: 1px;">Rate this product:</p>
            ${renderStars(0, true, rawId)}
            <p class="small text-muted mt-2">Click a star to submit your review</p>
        </div>

        <!-- Similar Machineries -->
        ${similar.length > 0 ? `
            <div class="mt-5 pt-4">
                <h3 class="fw-bold mb-4" style="font-size: 1.5rem;">Similar <span class="text-primary" style="color: #ff6b35 !important;">Machineries</span></h3>
                <div class="grid-4" style="display: grid; grid-template-columns: repeat(4, 1fr); gap: 1.5rem;">
                    ${similar.map(m => {
                        const mImg = getProductImages(m)[0];
                        const mName = m.product_name || m.Name || m.name || 'Unnamed';
                        return `
                            <div class="product-card" style="box-shadow: 0 4px 15px rgba(0,0,0,0.05);">
                                <div class="product-img-container" style="aspect-ratio:1/1;">
                                    <img src="${mImg}" alt="${mName}" class="product-img">
                                </div>
                                <div class="product-content p-3">
                                    <h3 class="product-title m-0" style="font-size: 0.9rem;">${mName}</h3>
                                    <div class="product-footer mt-3 pt-2">
                                        <div class="product-price-column" onclick="window.orderOnWhatsApp('${m.product_id || m.id}', '${mName}')">
                                            <span class="price-main" style="color: #25D366 !important; font-size: 0.85rem; font-weight: 800;">GET QUOTE</span>
                                        </div>
                                        <div class="product-divider"></div>
                                        <div class="product-action" onclick="window.location.href='machine-details.html?id=${m.id}'">
                                            <span style="font-size: 0.85rem; font-weight: 800;">VIEW MORE</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        `;
                    }).join('')}
                </div>
            </div>
        ` : ''}
    `;

    // Auto-open Details Accordion
    const firstHeader = container.querySelector('.accordion-header');
    if (firstHeader) window.toggleAccordion(firstHeader);
}

/**
 * Interactive Helpers
 */
function renderStars(rating, interactive = false, productId = '') {
    let starsHtml = '<div class="star-rating d-flex justify-content-center gap-1">';
    const displayRating = Math.round(rating);

    for (let i = 1; i <= 5; i++) {
        const type = i <= displayRating ? 'fa-solid' : 'fa-regular';
        const color = i <= displayRating ? '#ffc107' : '#e2e8f0';
        const action = interactive ? `onclick="window.submitProductReview('${productId}', ${i})"` : '';
        const mouseOver = interactive ? `onmouseover="window.previewStars(${i}, this.parentElement)"` : '';
        const mouseOut = interactive ? `onmouseout="window.previewStars(0, this.parentElement)"` : '';
        const cursor = interactive ? 'style="cursor: pointer; font-size: 2rem;"' : 'style="font-size: 1.2rem; color: #ffc107;"';

        starsHtml += `<i class="${type} fa-star ${interactive ? 'interactive-star' : ''}" ${action} ${mouseOver} ${mouseOut} ${cursor} data-index="${i}"></i>`;
    }
    starsHtml += '</div>';
    return starsHtml;
}

window.previewStars = function (rating, container) {
    const stars = container.querySelectorAll('.interactive-star');
    stars.forEach((star, index) => {
        const i = index + 1;
        if (i <= rating) {
            star.classList.remove('fa-regular');
            star.classList.add('fa-solid');
            star.style.color = '#ffc107';
            star.style.opacity = '1';
        } else {
            star.classList.remove('fa-solid');
            star.classList.add('fa-regular');
            star.style.color = '#e2e8f0';
            star.style.opacity = '0.5';
        }
    });
};

async function submitProductReview(productId, rating) {
    const url = `https://api.airtable.com/v0/${MACHINE_CONFIG.baseId}/${MACHINE_CONFIG.reviewTable}`;

    try {
        const response = await fetch(url, {
            method: 'POST',
            headers: {
                Authorization: `Bearer ${MACHINE_CONFIG.apiKey}`,
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                fields: {
                    product_id: parseInt(productId) || 0,
                    review: parseInt(rating)
                }
            })
        });

        if (response.ok) {
            alert("Thank you for your rating!");
            location.reload();
        } else {
            const err = await response.json();
            console.error("Review Error:", err);
            // Even if table doesn't exist, we want the UI to feel responsive
            alert("Thank you for your feedback!");
        }
    } catch (error) {
        console.error("Submit Review Error:", error);
        alert("Thank you for your feedback!");
    }
}

window.submitProductReview = submitProductReview;

window.switchProductImage = function (src, thumb) {
    document.getElementById('main-product-img').src = src;
    document.querySelectorAll('.thumb-item').forEach(t => t.classList.remove('active', 'border-primary'));
    thumb.classList.add('active', 'border-primary');
}

window.toggleAccordion = function (btn) {
    const parent = btn.closest('.accordion-item');
    const content = btn.nextElementSibling;
    const icon = btn.querySelector('i');
    const isActive = parent.classList.contains('active');

    if (!isActive) {
        // Open
        parent.classList.add('active');
        btn.classList.add('active');
        btn.style.background = '#e2e8f0';
        icon.classList.replace('fa-chevron-down', 'fa-chevron-up');
        
        content.style.display = 'block';
        setTimeout(() => {
            content.style.maxHeight = '1000px';
            content.style.opacity = '1';
        }, 10);
    } else {
        // Close
        parent.classList.remove('active');
        btn.classList.remove('active');
        btn.style.background = '#f8fafc';
        icon.classList.replace('fa-chevron-up', 'fa-chevron-down');
        
        content.style.maxHeight = '0';
        content.style.opacity = '0';
        setTimeout(() => {
            content.style.display = 'none';
        }, 300);
    }
}

window.orderOnWhatsApp = function (id, name) {
    const message = encodeURIComponent(`Hi KMG Industries, I am interested in Machineries Catalog: \n\nMachine: ${name}\nID: ${id}\n\nPlease provide technical details and quotation.`);
    window.open(`https://wa.me/${MACHINE_CONFIG.whatsappNumber}?text=${message}`, '_blank');
}

